# Site settings
title: 雪在飘，儿时梦想在燃烧
email: 396436290@qq.com
description: > # this means to ignore newlines until "baseurl:"
   之双是我最崇拜的人。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
github_username:  sona0402


markdown: kramdown

paginate: 4

author: sona

gems: [jekyll-paginate]

theme: jekyll-theme-hacker