# Site settings
title: Ashley Reardon
email: reardona@knights.ucf.edu
description: > # this means to ignore newlines until "baseurl:"
  Human Factors Engineer Intern
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/alr/" # the subpath of your site, e.g. /blog/
url: "https://reardona.github.io/alr/" # the base hostname & protocol for your site
github_username:  reardona

# Build settings
markdown: kramdown

paginate: 4

author: Ashley Reardon

gems: [jekyll-paginate]
