# Site settings
title: Objectiolog
email: objection@kakao.com
description: > # this means to ignore newlines until "baseurl:"
  computer system management
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://objectio.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username:  objectio

# Build settings
markdown: kramdown

paginate: 4

author: objectio

gems: [jekyll-paginate]
