# Site settings
title: 雪在飘，儿时梦想在燃烧
email: 396436290@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.renfakai.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  sona0402

# Build settings
markdown: kramdown

paginate: 4

author: sona

gems: [jekyll-paginate]

theme: jekyll-theme-hacker