# Site settings
title: indeex
email: imisslovelove@live.com
description: > # this means to ignore newlines until "baseurl:"
 Welcom to my website.
baseurl: "/book/" # the subpath of your site, e.g. /blog/
url: "http://indeex.org/book" # the base hostname & protocol for your site
twitter_username: imisslovelove
github_username:  houngkinghsi

# Build settings
markdown: kramdown

paginate: 4

author: houngking

gems: [jekyll-paginate]
